version: 1.0.0
project:
  name: Bot-RL-2
  timezone: UTC
  base_currency: USD
  random_seed: 42
  enable_env_override: true
paths:
  root_dir: .
  data_dir: f02_data
  raw_dir: f02_data/raw
  processed_dir: f02_data/processed
  logs_dir: logs
  reports_dir: reports
  cache_dir: f02_data/cache
  models_dir: f12_models
  config_versions_dir: f01_config/versions
  tmp_dir: tmp
  models:
    production_dir: f12_models/production
    staging_dir: f12_models/staging
    checkpoints_dir: f12_models/checkpoints
    experiments_dir: f12_models/experiments
  news_dir: f02_data/news
mt5_credentials:
  login: 52526121
  password: _lXfGlE7
  server: Alpari-MT5-Demo
download_defaults:
  symbols:
  - USDCAD
  timeframes:
  - H1
  lookback_bars: 2000
  batch_size: 50
  save_format: parquet
  align_to_session: true
  data_raw: f02_data/raw
  data_processed: f02_data/processed
timeframes:
- M1
- M5
- M30
- H4
- D1
- W1
n_candles_per_tf: 256
n_candles: 256
start_date: null
end_date: null
sessions:
  asia:
    start_utc: 00:00
    end_utc: 08:00
  london:
    start_utc: 08:00
    end_utc: '16:00'
  newyork:
    start_utc: '13:00'
    end_utc: '21:00'
features:
  pipeline:
    use_default_set: true
    include:
      indicators: true
      price_action: true
      fibonacci: true
      support_resistance: true
      volatility: true
  base_timeframe: M1
  shift_features_by: 1
  drop_na_head: true
  indicators:
  - div_rsi(14,2,classic)@M1
  - ema(close,20)@M5
  - sar(0.02,0.02,0.2)@M1
  - supertrend(10,3)@M5
  - adx(14)@M30
  - macd(12,26,9)@M1
  - atr(14)@M1
  - bbands(close,20,2)@M1
  - donchian(20)@H1
  - rsi(14)@M1
  - stoch(14,3)@M1
  - vwap@M1
  - cmf(20)@M1
  - pat_engulf@M5
  - pat_engulf@H1
  - pat_engulf@H4
  - pat_engulf@D1
  - pat_doji(atr_ratio_thresh=0.12,range_ratio_thresh=0.25,atr_win=14)@M5
  - pat_doji(atr_ratio_thresh=0.12,range_ratio_thresh=0.25,atr_win=14)@H1
  - pat_doji(atr_ratio_thresh=0.12,range_ratio_thresh=0.25,atr_win=14)@H4
  - pat_doji(atr_ratio_thresh=0.12,range_ratio_thresh=0.25,atr_win=14)@D1
  - pat_pin(ratio=2.0)@M5
  - pat_pin(ratio=2.0)@H1
  - pat_pin(ratio=2.0)@H4
  - pat_pin(ratio=2.249999999999999)@D1
  - pat_hammer_star(min_body_frac=0.0,wick_ratio=2.0,opp_wick_k=1.25)@M5
  - pat_hammer_star(min_body_frac=0.0,wick_ratio=2.0,opp_wick_k=1.25)@H1
  - pat_hammer_star(min_body_frac=0.0,wick_ratio=2.0,opp_wick_k=1.25)@H4
  - pat_hammer_star(min_body_frac=0.0,wick_ratio=2.549999999999998,opp_wick_k=1.25)@D1
  - pat_harami@M5
  - pat_harami@H1
  - pat_harami@H4
  - pat_harami@D1
  - pat_inside_outside(min_range_k_atr=0.50,atr_win=14)@M5
  - pat_inside_outside(min_range_k_atr=0.50,atr_win=14)@H1
  - pat_inside_outside(min_range_k_atr=0.50,atr_win=14)@H4
  - pat_inside_outside(min_range_k_atr=1.5000000000000009,atr_win=14)@D1
  - pat_marubozu(wick_frac=0.10)@M5
  - pat_marubozu(wick_frac=0.10)@H1
  - pat_marubozu(wick_frac=0.10)@H4
  - pat_marubozu(wick_frac=0.10)@D1
  - pat_tweezer(tol_frac=null,tol_k=0.25,tol_mode="atr_price",atr_win=14)@M5
  - pat_tweezer(tol_frac=null,tol_k=0.25,tol_mode="atr_price",atr_win=14)@H1
  - pat_tweezer(tol_frac=null,tol_k=0.25,tol_mode="atr_price",atr_win=14)@H4
  - pat_tweezer(tol_frac=null,tol_k=1.3877787807814457e-17,tol_mode="atr_price",atr_win=14)@D1
  - pat_3soldiers_crows(min_body_atr=0.25,atr_win=14)@M5
  - pat_3soldiers_crows(min_body_atr=0.25,atr_win=14)@H1
  - pat_3soldiers_crows(min_body_atr=0.25,atr_win=14)@H4
  - pat_3soldiers_crows(min_body_atr=0.3,atr_win=14)@D1
  - pat_morning_evening(small_body_atr=0.30,atr_win=14)@M5
  - pat_morning_evening(small_body_atr=0.30,atr_win=14)@H1
  - pat_morning_evening(small_body_atr=0.30,atr_win=14)@H4
  - pat_morning_evening(small_body_atr=0.10000000000000002,atr_win=14)@D1
  - pat_piercing_dark(min_body_ratio=0.20)@M5
  - pat_piercing_dark(min_body_ratio=0.20)@H1
  - pat_piercing_dark(min_body_ratio=0.20)@H4
  - pat_piercing_dark(min_body_ratio=0.65)@D1
  - pat_belt(wick_frac=0.10)@M5
  - pat_belt(wick_frac=0.10)@H1
  - pat_belt(wick_frac=0.10)@H4
  - pat_belt(wick_frac=0.0)@D1
  - pivots@M1
  - sr(2,500)@M1
  - fibo(2)@M1
  fibonacci:
    enabled: true
    swing_window_bars: 200
    cluster_merge_pips: 20
    order_planner:
      use_atr_for_sl_tp: true
      sl_atr_mult: 1.5
      tp_atr_mult: 2.0
      atr_length: 14
      partial_take_profits:
        enabled: true
        levels_r_multiple:
        - 1.0
        - 2.0
        portions:
        - 0.5
        - 0.5
    retracement_ratios:
    - 0.236
    - 0.382
    - 0.5
    - 0.618
    - 0.786
    - 0.886
    extension_ratios:
    - 1.272
    - 1.618
    - 2.0
    - 2.618
    - 3.618
    golden_zone:
      ratios:
      - 0.382
      - 0.618
    cluster:
      min_members: 2
      min_score: 5.0
      leg_age_decay: 0.9
    leg_selection:
      max_legs_per_tf: 3
      lookback_bars: 2000
      prefer_body: false
      prominence_min: null
    rsi:
      length: 14
      overbought: 70
      oversold: 30
    tf_overrides:
      M15:
        leg_selection:
          max_legs_per_tf: 5
      H1:
        leg_selection:
          max_legs_per_tf: 4
      H4:
        leg_selection:
          max_legs_per_tf: 3
      D1:
        leg_selection:
          max_legs_per_tf: 2
      W1:
        leg_selection:
          max_legs_per_tf: 1
    symbol_overrides:
      XAUUSD:
        rsi:
          overbought: 72
          oversold: 28
      EURUSD: {}
      GBPUSD: {}
      USDJPY: {}
      USDCHF: {}
      USDCAD: {}
      AUDUSD: {}
      NZDUSD: {}
    harmonics:
      enabled: false
      patterns:
      - AB=CD
      ratio_tolerance: 0.05
    caching:
      enabled: false
      ttl_bars: 500
  time_features:
    add_hour_of_day: true
    add_day_of_week: true
    add_session_flags: true
    normalize_time: true
  support_resistance:
    enabled: true
    lookback_bars: 1500
    cluster_tolerance_pips: 15
    sr_advanced:
      common:
        atr_window: 14
        max_bars_alive: 5
        w_size: 0.5
        w_age: 0.3
        w_touch: 0.2
      fvg:
        lookback: 2
        min_size_pct_of_atr: 0.35
      supply_demand:
        base_len: 3
        base_atr_max: 1.0
        impulse_atr_min: 0.8
      order_block:
        body_atr_min: 0.4
        wick_ratio_max: 1.0
        bos_lookback: 8
      breaker_flip:
        lookback: 20
        ob_body_atr_min: 0.35
        ob_wick_ratio_max: 1.0
        ob_bos_lookback: 10
      liq_sweep:
        lookback: 6
        min_tail_atr: 0.4
      sr_fusion:
        ema_span: 5
        age_norm: 6.0
        enter_th: 0.35
        exit_th: 0.25
        cooldown_bars: 3
        min_conf: 0.25
        tie_eps: 0.02
        confirm_col: null
      overrides:
        XAUUSD:
          H1:
            supply_demand:
              base_atr_max: 1.0
              impulse_atr_min: 0.8
            sr_fusion:
              enter_th: 0.35
              exit_th: 0.25
  price_action_params:
    anti_lookahead: true
    market_structure:
      lookback: 3
    regime:
      atr_window: 22
      width_window: 30
      slope_window: 13
      spike_thr_atr: 1.4
      channel_slope_thr: 0.30000000000000004
    breakouts:
      range_window: 25
      min_periods: 8
      confirm_closes: 1
      retest_lookahead: 8
      fail_break_lookahead: 2
    microchannels:
      min_len: 5
      near_extreme_thr: 0.25
    mtf:
      bias_window_base: 15
      bias_window_higher: 6
      fillna_confluence: 0.5
    confluence:
      weights:
        structure: 0.3
        zones: 0.25
        imbalance: 0.2
        mtf: 0.25
      strong_entry_threshold: 0.64
      filter_threshold: 0.36
env:
  observation:
    resample_to_base_tf: M5
    standardize_inputs: true
    clip_values: true
    clip_range:
    - -5
    - 5
  action_space:
    type: discrete
    discrete_actions:
    - HOLD
    - OPEN_LONG
    - OPEN_SHORT
    - CLOSE_POSITION
    fractional_position_sizes:
    - 0.25
    - 0.5
    - 1.0
  reward:
    type: risk_adjusted_pnl
    params:
      dd_penalty: 2.5
      trade_cost_penalty: 1.0
  termination:
    max_episode_steps: 5000
    stop_on_margin_call: true
    stop_on_max_drawdown_pct: 0.2
  window_size: 128
  normalize: true
  split:
    train:
    - '2025-08-21'
    - '2025-08-25'
    val:
    - '2025-08-25'
    - '2025-08-26'
    test:
    - '2025-08-26'
    - '2099-12-31'
  features_whitelist:
  - __rsi_
  - __macd_
  - __ema_close_
  - __atr_
  - __bb_
  - __stoch_
  - __sar_
  - __supertrend_
rl:
  algorithm: PPO
  policy: MlpPolicy
  hyperparams:
    ppo:
      n_steps: 2048
      batch_size: 256
      gamma: 0.99
      gae_lambda: 0.95
      clip_range: 0.2
      ent_coef: 0.01
      vf_coef: 0.5
      max_grad_norm: 0.5
      learning_rate: 0.0003
      target_kl: 0.02
    sac:
      learning_rate: 0.0003
      buffer_size: 1000000
      batch_size: 256
      gamma: 0.99
      tau: 0.005
      ent_coef: auto
      train_freq: 1
      gradient_steps: 1
training:
  total_timesteps: 2000000
  eval_freq_steps: 25000
  checkpoint_interval_steps: 50000
  max_checkpoints_to_keep: 10
  resume_if_exists: true
  early_stop:
    enabled: true
    metric: eval/sharpe
    patience_evals: 5
    min_delta: 0.01
  experiment_name: ppo_baseline_mtf
evaluation:
  backtest:
    commissions_per_lot_usd: 7.0
    slippage_pips_mean: 2
    slippage_pips_std: 1
    reuse_historical_spread: true
    cross_validation:
      enabled: true
      folds: 3
      method: expanding_window
      min_trades_per_fold: 30
  acceptance_gates:
    sharpe_min: 0.8
    profit_factor_min: 1.2
    winrate_min: 0.48
    max_drawdown_max: 0.12
    turnover_max_per_day: 80
    min_trades_total: 200
risk:
  risk_per_trade: 0.01
  max_daily_loss_pct: 0.03
  max_total_drawdown_pct: 0.2
  position_sizing:
    method: fixed_fractional
    min_lot: 0.01
    lot_step: 0.01
    max_lot: 10.0
    use_atr_for_sl: true
    sl_atr_mult: 1.5
    tp_atr_mult: 2.0
    breakeven:
      enabled: true
      at_r_multiple: 1.0
    trailing:
      enabled: true
      type: chandelier
      atr_period: 22
      atr_mult: 3.0
  position_limits:
    max_open_positions: 1
    max_positions_per_symbol: 1
    cooldown_minutes_after_stop: 15
executor:
  live_trading: false
  order:
    type: market
    retry_attempts: 3
    timeout_sec: 3.0
    partial_fill_handling: cancel_remaining
  slippage_cap_pips: 6
  sync_with_env_behaviors: true
  canary_deployment:
    enabled: true
    volume_multiplier: 0.5
    min_duration_minutes: 60
    promote_criteria:
      min_trades: 5
      min_pnl_usd: 0.0
      max_dd_live: 0.03
  rollback:
    on_breach: true
self_optimize:
  schedule:
    daily_utc: '22:30'
    weekly_utc: Fri 21:00
  steps:
    data_refresh: true
    hparam_search:
      enabled: false
      max_trials: 20
      sampler: tpe
      space:
        pa.market_structure.lookback:
        - 2
        - 3
        - 4
        - 5
        pa.regime.atr_window:
          min: 10
          max: 24
          step: 1
        pa.regime.width_window:
          min: 10
          max: 30
          step: 1
        pa.regime.slope_window:
          min: 6
          max: 20
          step: 1
        pa.regime.spike_thr_atr:
          choices:
          - 1.4
          - 1.6
          - 1.8
          - 2.0
          - 2.2
          - 2.5
        pa.regime.channel_slope_thr:
          min: 0.1
          max: 0.35
          step: 0.05
        pa.breakouts.range_window:
          min: 6
          max: 30
          step: 1
        pa.breakouts.min_periods:
          rule: min_periods = max(3, range_window//3)
        pa.breakouts.confirm_closes:
          choices:
          - 1
          - 2
          - 3
        pa.breakouts.retest_lookahead:
          choices:
          - 3
          - 5
          - 8
        pa.breakouts.fail_break_lookahead:
          choices:
          - 2
          - 3
          - 5
        pa.microchannels.min_len:
          choices:
          - 3
          - 4
          - 5
          - 6
        pa.microchannels.near_extreme_thr:
          choices:
          - 0.1
          - 0.15
          - 0.2
          - 0.25
          - 0.3
        pa.mtf.bias_window_base:
          min: 6
          max: 16
          step: 1
        pa.mtf.bias_window_higher:
          min: 6
          max: 20
          step: 1
        pa.mtf.fillna_confluence:
          choices:
          - 0.3
          - 0.5
        pa.confluence.weights:
          choices:
          - - 0.3
            - 0.3
            - 0.2
            - 0.2
          - - 0.35
            - 0.25
            - 0.2
            - 0.2
          - - 0.25
            - 0.35
            - 0.2
            - 0.2
          - - 0.3
            - 0.25
            - 0.2
            - 0.25
        pa.confluence.strong_entry_threshold:
          min: 0.6
          max: 0.8
          step: 0.02
        pa.confluence.filter_threshold:
          min: 0.3
          max: 0.5
          step: 0.02
    finetune:
      enabled: true
      steps: 75000
      mix_replay_with_recent_pct: 0.2
    backtest:
      enabled: true
    deploy:
      staging_then_promote: true
  acceptance_gates:
    sharpe_min: 0.8
    profit_factor_min: 1.2
    winrate_min: 0.48
    max_drawdown_max: 0.12
    turnover_max_per_day: 80
    min_trades_total: 200
  alerts_on_change: true
monitoring:
  logging:
    level: INFO
    to_console: true
    to_file: true
    file_path: logs/bot.log
    rotate_max_bytes: 10485760
    rotate_backups: 5
    jsonl: true
  alerts:
    enable_telegram: true
    telegram:
      bot_token_env: TELEGRAM_BOT_TOKEN
      chat_id_env: TELEGRAM_CHAT_ID
    email:
      enabled: false
      smtp_host: ''
      smtp_user_env: SMTP_USER
      smtp_pass_env: SMTP_PASS
      to: []
  reporting:
    daily_summary: true
    weekly_summary: true
    include_equity_curve: true
    include_trade_log: true
safety:
  hard_kill_switch:
    enabled: true
    conditions:
    - name: max_daily_loss
      metric: live/daily_loss_pct
      op: '>='
      value: 0.03
    - name: max_drawdown_total
      metric: live/total_drawdown_pct
      op: '>='
      value: 0.2
    - name: too_many_trades
      metric: live/trades_per_day
      op: '>'
      value: 120
  news_filter:
    enabled: true
    high_impact_freeze_minutes_before: 31
    high_impact_freeze_minutes_after: 16
    medium_impact_freeze_minutes_before: 16
    medium_impact_freeze_minutes_after: 11
    sources:
    - forexfactory
    currencies:
    - USD
    - EUR
    - GBP
    - JPY
per_symbol_overrides:
  XAUUSD:
    risk:
      risk_per_trade: 0.005
      sl_atr_mult: 1.8
    evaluation:
      acceptance_gates:
        sharpe_min: 0.9
        max_drawdown_max: 0.1
cicd:
  enabled: false
  run_unit_tests_on_push: true
  run_backtest_on_main: true
  artifact_retention_days: 30
scripts:
  download_data: scripts/run_download.py
  train: scripts/run_train.py
  backtest: scripts/run_backtest.py
  deploy: scripts/run_deploy.py
  self_optimize: scripts/run_self_optimize.py
secrets:
  use_env: true
  env_keys:
    MT5_LOGIN: MT5_LOGIN
    MT5_PASSWORD: MT5_PASSWORD
    MT5_SERVER: MT5_SERVER
    MT5_PATH: MT5_PATH
    TELEGRAM_BOT_TOKEN: TELEGRAM_BOT_TOKEN
    TELEGRAM_CHAT_ID: TELEGRAM_CHAT_ID
__cfg_path__: f01_config\config.yaml
